# 计算能力和多样的计算功能

In [1]:
# 使用map()
l = [150, 166, 183, 170]
print(list(map(lambda x: x+3 , l)))

# 使用numpy
import numpy as np
l = np.array([150, 166, 183, 170])
print(l+3)


[153, 169, 186, 173]
[153 169 186 173]


## 矩阵运算
np.dot() 计算两个向量的点积；对于矩阵，它执行矩阵乘法

np.outer() 矩阵外积，外积将两个向量的所有可能组合相乘，形成一个矩阵

np.inner() 矩阵内积，对于 1D 向量，np.inner() 与 np.dot() 基本相同，计算两个向量的点积，但对于多维数组，会对每一行计算内积

np.cross() 叉积是仅定义在三维空间中的操作，计算两个三维向量的向量积

In [2]:
#np.dot() 一维点积
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.dot(a, b)  # 1*4 + 2*5 + 3*6 = 32
print("点积",result)

#np.dot() 二维矩阵相乘
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("矩阵乘法",np.dot(A, B))

#np.outer()
print("矩阵外积",np.outer(a, b))

#np.inner()
print("矩阵内积 一维",np.inner(a, b))
print("矩阵内积 多维",np.inner(A, B))

#np.cross()
print("叉积",np.cross(a, b))


点积 32
矩阵乘法 [[19 22]
 [43 50]]
矩阵外积 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
矩阵内积 一维 32
矩阵内积 多维 [[17 23]
 [39 53]]
叉积 [-3  6 -3]


## 数据统计分析

np.max(), np.min()

a.max(), a.min()

a.prod() 或者 np.prod(a) 计算累乘

np.mean() 计算均值

np.median() 计算中位数

np.std() 计算标准差


In [3]:
a = np.array([150, 166, 183, 170])
print("累乘：", a.prod())
print("总数：", a.size)   
                 
a = np.array([0, 1, 2, 3])
print("非零总数：", np.count_nonzero(a))

累乘： 774639000
总数： 4
非零总数： 3


In [4]:
month_salary = [1.2, 20, 0.5, 0.3, 2.1]
print("平均工资：", np.mean(month_salary))
print("工资中位数：", np.median(month_salary))
print("标准差：", np.std(month_salary))

平均工资： 4.82
工资中位数： 1.2
标准差： 7.61614075500184


## 其他常用的计算函数
np.argmax() 获取这个最大数值的序号

np.argmin() 获取这个最大数值的序号

np.ceil() 和 np.floor() 取整处理，抹除小数部分

np.clip() 上下界限的值截取

In [5]:
a = np.array([150, 166, 183, 170])
name = ["小米", "OPPO", "Huawei", "诺基亚"]
high_idx = np.argmax(a)
low_idx = np.argmin(a)
print("{} 最高".format(name[high_idx]))
print("{} 最矮".format(name[low_idx]))


Huawei 最高
小米 最矮


In [6]:
a = np.array([150.1, 166.4, 183.7, 170.8])
print("ceil:", np.ceil(a))
print("floor:", np.floor(a))


ceil: [151. 167. 184. 171.]
floor: [150. 166. 183. 170.]


In [7]:
a = np.array([150.1, 166.4, 183.7, 170.8])
print("clip:", a.clip(160, 180))


clip: [160.  166.4 180.  170.8]
