# 挑选出符合你要求的数据
```
数组的索引从0开始，可以用方括号[]来访问元素。
第一个数据是[0][0]
```


In [ ]:
import numpy as np

a = np.array([1, 2, 3])
print("a[0]:", a[0])
print("a[1]:", a[1])

In [ ]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

# 选第 2 行所有数
print("b[1]:", b[1])   

# 选第 2 行，第 1 列的数
print("b[1,0]:", b[1,0])   

# 这个看着有点纠结，如果对应到数据，
# 第一个拿的是数据位是 [1,2]
# 第二个拿的是 [0,3]
print("b[[1,0],[2,3]]:", b[[1,0],[2,3]])    # 选第 2 行的第 3 列，和第 1 行的第 4 列
print("b[np.ix_([1, 0], [2, 3])]:", b[np.ix_([1, 0], [2, 3])]) # 选第 2 行和第 1 行 的 第 3 列和第 4 列

## 切片划分

In [ ]:
a = np.array([1, 2, 3])
print("a[0:2]:", a[0:2])    # [1 2]不包括最右端的元素
print("a[1:]:", a[1:])
print("a[1:]:", a[1:-1])
print("a[-2:]:", a[-2:])

In [12]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print("b[:2]:", b[:2])
print("b[:2, :3]:", b[:2, :3])
print("b[1:3, -2:]:", b[1:3, -2:])

b[:2]: [[1 2 3 4]
 [5 6 7 8]]
b[:2, :3]: [[1 2 3]
 [5 6 7]]
b[1:3, -2:]: [[ 7  8]
 [11 12]]


## 条件筛选
where()函数可以根据条件筛选数组中的元素。


In [15]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

condition = a > 7
print(condition)
print(a[condition])
#或者写成 print(a[a > 7])

#下面满足条件的，都改成 -1，不满足的，都还是 a 里面的数字。
condition = a > 7
print(np.where(condition, -1, a)) # a也可以改成其他数据


[[False False False False]
 [False False False  True]
 [ True  True  True  True]]
[ 8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7 -1]
 [-1 -1 -1 -1]]
