# 标准数据生成

怎么带着数值初始化，可以带着怎样的数值初始化

### 创建统一数据

np.zeros()  # 创建全0数组
np.ones()   # 创建全1数组
np.empty()  # 创建未初始化的数组
np.arange()  # 创建等差数组
np.linspace()  # 创建等间距数组
np.random.rand()  # 创建随机数组
np.full()    # 创建指定值数组

In [9]:
import numpy as np

zeros = np.zeros([2, 3])
print("zeros:\n", zeros)

ones = np.ones([3, 2])
print("\nones:\n", ones)

nines = np.full([2,3], 9)
print("\nnines:\n", nines)

identity = np.identity(3)
print("\nidentity:\n", identity)

random = np.random.rand(2, 3)
print("\nrandom:\n", random)

empty = np.empty([2, 3])
print("\nempty:\n", empty)
#注意，虽然乱乱的，但是它不是随机数哦，你不能把它当随机数使用
# 首先，可以当成一个 placeholder，一个容器先放着，之后慢慢放数据
# 创建起来比 ones, zeros, full 都快一点点

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

nines:
 [[9 9 9]
 [9 9 9]]

identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

random:
 [[0.17613907 0.92357226 0.04016408]
 [0.58873357 0.21518226 0.27295933]]

empty:
 [[0.17613907 0.92357226 0.04016408]
 [0.58873357 0.21518226 0.27295933]]


In [10]:
data = np.array([
[1,2,3],
[4,5,6]
], dtype=np.int64)

ones = np.ones(data.shape, dtype=data.dtype)
ones_like = np.ones_like(data)

print("ones:", ones.shape, ones.dtype)
print("ones_like:", ones_like.shape, ones_like.dtype)
print("ones_like value:\n", ones_like)

print(np.zeros_like(data))
print(np.full_like(data, 6))


ones: (2, 3) int64
ones_like: (2, 3) int64
ones_like value:
 [[1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]]
[[6 6 6]
 [6 6 6]]


### 创建规则数据

np.arange()  # 等差数列
np.linspace()  # 创建等间距数组
np.random.rand()  # 随机数
np.random.randn()  # 标准正态分布随机数
np.random.randint()  # 随机整数

In [11]:
print("python range:", list(range(5)))  #列表
print("numpy arange:", np.arange(5))    #数组

#同样，np.arange() 也可以像 range() 一样，对范围做自定义更变或跳跃取值。

# (start, end, step) 
print("python range:", list(range(3, 10, 2)))
print("numpy arange:", np.arange(3, 10, 2))

# 在画折线图的时候，我想要连续在一个区间内取间隔一致的数据点
# np.linspace()  # 创建等间距数组

# (start, end, num)
print("linspace:", np.linspace(-1, 1, 5))


python range: [0, 1, 2, 3, 4]
numpy arange: [0 1 2 3 4]
python range: [3, 5, 7, 9]
numpy arange: [3 5 7 9]
linspace: [-1.  -0.5  0.   0.5  1. ]
